'use strict';
// Generate deployment adapters from the portal's existing Blak palette.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const { blakTheme, tokens, tokenCSS } = require('../../apps/portal/theme');
const check = process.argv.includes('--check');
function write(file, contents) {
  const target = path.join(root, file);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== contents) throw new Error(`Stale generated theme: ${file}`);
  } else fs.writeFileSync(target, contents);
}
write('services/app-roles/content-sources.json', fs.readFileSync(path.join(root, 'apps/portal/content-sources.json'), 'utf8'));
write('services/hermes-sync/content-sources.json', fs.readFileSync(path.join(root, 'apps/portal/content-sources.json'), 'utf8'));
const { INTEGRATIONS } = require('../../apps/portal/integration');
const grants = JSON.stringify(Object.fromEntries(Object.entries(INTEGRATIONS).filter(([, value]) => value.group || value.roleGroups).map(([app, { group, roleGroups }]) => [app, { group, roleGroups }])), null, 2) + '\n';
write('services/app-roles/app-grants.json', grants);
write('services/hermes-sync/app-grants.json', grants);
for (const file of ['access.py', 'directory.py', 'http_client.py']) {
  write('services/hermes-sync/' + file, '# Generated from services/app-roles/' + file + '. Do not edit.\n' + fs.readFileSync(path.join(root, 'services/app-roles', file), 'utf8'));
}
const theme = JSON.stringify(blakTheme(), null, 2) + '\n';
write('deploy/k3s/micro/blak-theme/theme.json', theme);
const { LOGO_SVG: logo } = require('../../apps/portal/brand');
write('deploy/k3s/micro/blak-theme/assets-logo.svg', logo+'\n');
write('deploy/k3s/micro/50-drive-theme.yaml', '# Generated by node scripts/brand/generate.js. Do not edit.\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: drive-theme\n  namespace: blak-micro\ndata:\n  theme.json: |\n' + theme.trimEnd().split('\n').map(line=>'    '+line).join('\n') + '\n  logo.svg: |\n    ' + logo + '\n');
const background = fs.readFileSync(path.join(root, 'apps/portal/login-background.png'));
const backgroundTarget = path.join(root, 'services/workspace-shell/login-background.png');
if (check) { if (!fs.readFileSync(backgroundTarget).equals(background)) throw new Error('Stale shared login background'); }
else fs.writeFileSync(backgroundTarget, background);
const fontCSS=fs.readFileSync(path.join(root,'apps/portal/fonts.css'),'utf8');
write('services/workspace-shell/fonts.css',fontCSS);
for(const name of ['InterVariable.woff2','OFL.txt']) {
  const source=fs.readFileSync(path.join(root,'apps/portal/fonts',name));
  const target=path.join(root,'services/workspace-shell/fonts',name);
  if(check) {if(!fs.existsSync(target)||!fs.readFileSync(target).equals(source)) throw Error('Stale shared font: '+name);}
  else {fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,source);}
}
const t = tokens.dark;
// Vault styling is bundled into its own immutable image; no shared shell script.
function vaultPalette(p) {
  const roles={'background':p.surface,'background-alt':p['surface-raised'],'background-alt2':p['surface-base'],'background-alt3':p['surface-base'],'background-alt4':p['surface-hover'],'text-main':p['text-primary'],'text-muted':p['text-secondary'],'primary-100':p['surface-selected'],'primary-600':p.primary,'primary-700':p['primary-hover'],'secondary-100':p['surface-raised'],'secondary-300':p.border,'secondary-500':p['border-strong']};
  const modern={'bg-primary':p.surface,'bg-secondary':p['surface-base'],'bg-tertiary':p['surface-raised'],'bg-quaternary':p['surface-hover'],'bg-brand':p.primary,'bg-brand-strong':p['primary-hover'],'bg-brand-soft':p['surface-selected'],'bg-brand-softer':p['surface-selected'],'fg-body':p['text-primary'],'fg-heading':p['text-primary'],'fg-body-subtle':p['text-secondary'],'fg-brand':p.primary,'fg-brand-strong':p['primary-hover'],'border-base':p.border,'border-light':p.border,'border-muted':p.border,'border-strong':p['border-strong'],'border-brand':p.primary,'border-brand-strong':p['primary-hover'],'border-focus':p.focus,'nav-bg-primary':p['surface-base'],'nav-bg-secondary':p.surface,'nav-fg-primary':p['text-primary'],'nav-fg-secondary':p['text-primary'],'nav-bg-primary-strong':p['surface-selected'],'nav-bg-secondary-strong':p['surface-selected'],'nav-bg-primary-hover':p['surface-hover'],'nav-bg-secondary-hover':p['surface-hover']};
  return Object.entries(roles).map(([key,value])=>'--color-'+key+':'+value.slice(1).match(/../g).map(v=>parseInt(v,16)).join(' ')+';').join('')+
    Object.entries(modern).map(([key,value])=>'--color-'+key+':'+value+';').join('');
}
write('services/vault/brand.css',fontCSS.replaceAll('/_blak/fonts/','/fonts/')+'\n'+
  ':root,.theme_light{'+vaultPalette({...t,...tokens.light})+'}\n.theme_dark{'+vaultPalette(t)+'}\n'+
  'body,input,button,select,textarea{font-family:var(--blak-font-sans)!important}\n'+
  '.blak-vault-brand{display:flex;align-items:center;gap:10px;min-height:48px;padding:8px 20px;background:'+t['surface-base']+';color:'+t['text-primary']+';border-bottom:1px solid '+t.border+'}\n'+
  '.blak-vault-brand a{display:inline-flex;border-radius:4px}.blak-vault-brand a:focus-visible{outline:2px solid '+t.focus+';outline-offset:3px}.blak-vault-brand strong{font-size:15px}.blak-vault-brand span{margin-left:auto;font-size:12px;color:'+t['text-secondary']+'}\n'+
  'a[aria-label="Password Manager"][href="#/"] bit-svg{visibility:hidden}a[aria-label="Password Manager"][href="#/"]::after{content:"Blak Vault";position:absolute;inset:16px 12px;display:flex;align-items:center;padding-left:44px;background:url(/images/blak-logo.svg) no-repeat left center/32px 32px;font-size:18px;font-weight:600}\n'+
  '.tw-bg-primary-600,.tw-bg-bg-brand,.tw-bg-bg-brand-strong{color:'+t['on-primary']+'!important}@media(max-width:480px){.blak-vault-brand{padding-inline:12px}.blak-vault-brand span{display:none}}\n');
const identityCSS = `${fontCSS}\n${tokenCSS}
:host,:root{--pf-global--BackgroundColor--100:${t.surface};--pf-global--BackgroundColor--200:${t['surface-base']};--pf-global--Color--100:${t['text-primary']};--pf-global--Color--200:${t['text-secondary']};--pf-c-page--BackgroundColor:${t['surface-base']};--pf-c-page__main-section--BackgroundColor:${t.surface};--pf-c-card--BackgroundColor:${t['surface-raised']};--pf-c-card--Color:${t['text-primary']};--pf-global--primary-color--100:${t.primary};--pf-global--link--Color:${t.info};--pf-c-page__header--BackgroundColor:${t['surface-base']}}
:host{color:${t['text-primary']};font-family:Inter,system-ui,sans-serif;--pf-global--FontFamily--sans-serif:Inter,system-ui,sans-serif;--pf-global--FontFamily--heading--sans-serif:Inter,system-ui,sans-serif}.pf-c-page,.pf-c-page__main,.pf-c-page__main-section,.pf-c-page__header{background:${t['surface-base']}!important;color:${t['text-primary']}!important}
body{background:${t['surface-base']}!important;color:${t['text-primary']}!important;font-family:Inter,system-ui,sans-serif}
[class*="login__main"],[class*="card"],[class*="modal"]{background:${t.surface}!important;border-color:${t['border-subtle']}!important}
.pf-c-login__main{border-radius:16px;box-shadow:0 16px 48px #0005;overflow:hidden}
.pf-c-login__main-header.pf-c-brand{padding-block:28px 12px}
.branding-logo{width:104px!important;height:104px!important;max-width:100%;object-fit:contain}
@media(max-width:600px){.branding-logo{width:72px!important;height:72px!important}.pf-c-login__main-header.pf-c-brand{padding-block:20px 8px}}
button[type=submit],[class*="button"][class*="primary"]{background:${t.primary}!important;color:${t['on-primary']}!important;font-weight:600!important}
button[type=submit]:hover{background:${t['primary-hover']}!important}
h1,h2{font-family:Inter,system-ui,sans-serif!important;color:${t['text-primary']}!important}label{color:${t['text-secondary']}!important}a{color:${t.info}!important}
input{background:${t['surface-raised']}!important;border-color:${t.border}!important;color:${t['text-primary']}!important}input:focus{border-color:${t.focus}!important}
`;
write('scripts/deploy/ak-brand.py', '# Generated by node scripts/brand/generate.js.\nfrom authentik.brands.models import Brand\n\nCSS = """\n' + identityCSS + '"""\nbrand = Brand.objects.get(default=True)\nbrand.branding_title = "Blak ID"\nbrand.branding_default_flow_background = "https://id.workspace.example.com/_blak/login-background.png"\nbrand.branding_logo = "https://id.workspace.example.com/_blak/logo.svg"\nbrand.branding_favicon = "https://id.workspace.example.com/_blak/logo.svg"\nbrand.branding_custom_css = CSS\nbrand.save()\nfrom authentik.flows.models import Flow\nFlow.objects.filter(slug="default-authentication-flow").update(title="Welcome to Blak ID")\nfrom authentik.core.models import Application\nfor slug,name in {"opencloud":"Blak Drive","blak-portal":"Blak Workspace","outline":"Blak Knowledge","hermes":"Blak Hermes","kaneo":"Blak Projects","openproject":"Blak Projects","rocketchat":"Blak Chat","blak-forms":"Blak Forms","blak-crm":"Blak CRM","blaksmith":"BlakSmith","blak-eyes":"BlakEyes"}.items():\n    Application.objects.filter(slug=slug).update(name=name,meta_icon="https://id.workspace.example.com/_blak/logo.svg")\nprint("BRAND_CSS_OK")\n');
// App adapters retain upstream trademarks and interaction patterns.
const hermesCSS = `${tokenCSS}
html,body{font-family:Inter,system-ui,sans-serif!important}
html.dark{--color-gray-50:${t['sand-50']};--color-gray-100:${t['text-primary']};--color-gray-200:${t['text-secondary']};--color-gray-300:${t['text-secondary']};--color-gray-400:${t['text-muted']};--color-gray-500:${t['border-strong']};--color-gray-600:${t.border};--color-gray-700:${t['surface-hover']};--color-gray-800:${t['surface-raised']};--color-gray-850:${t.surface};--color-gray-900:${t.surface};--color-gray-950:${t['surface-base']}}
html:not(.dark){color-scheme:light;--color-white:${tokens.light['surface-raised']};--color-black:${tokens.light['text-primary']};--color-gray-50:${tokens.light.surface};--color-gray-100:${tokens.light['surface-base']};--color-gray-200:${tokens.light['border-subtle']};--color-gray-300:${tokens.light.border};--color-gray-400:${tokens.light['text-muted']};--color-gray-500:${tokens.light['text-secondary']};--color-gray-600:${tokens.light['text-secondary']};--color-gray-700:${tokens.light['text-primary']};--color-gray-800:${tokens.light['text-primary']};--color-gray-900:${tokens.light['text-primary']}}
html.dark body{background:${t.surface};color:${t['text-primary']}}
:focus-visible{outline-color:${t.focus}!important}
::selection{background:${t['water-700']};color:${t['sand-50']}}
`;
function chatRoles(palette) {
  return {
    'button-color-primary-default':t['on-primary'],'button-color-primary-hover':t['on-primary'],
    'button-background-primary-default':t.primary,'button-background-primary-hover':t['primary-hover'],
    'stroke-highlight':t.focus,'font-info':t.info,'surface-light':palette.surface,
    'surface-tint':palette['surface-base'],'surface-room':palette.surface,
    'surface-dark':palette['surface-base'],'surface-sidebar':palette['surface-base'],
    'font-default':palette['text-primary'],'font-secondary-info':palette['text-secondary'],
    'font-sidebar-default':palette['text-primary'],'stroke-light':palette['border-subtle'],
  };
}
function chatPalette(palette) {
  return Object.entries(chatRoles(palette)).map(([name,value])=>`--rcx-color-${name}:${value}!important`).join(';');
}
const chatCSS = `:root,body{${chatPalette(tokens.light)};font-family:Inter,system-ui,sans-serif}
.rcx-darkmode,.rcx-darkmode body,[data-theme="dark"],[data-theme="dark"] body{${chatPalette(t)}}
.rcx-sidebar--main{background:${t['surface-base']}!important}
`;
// Kaneo uses shadcn design tokens; append after its stylesheet via the deployment adapter.
const kaneoCSS = `:root{--primary:${t.primary};--primary-foreground:${t['on-primary']};--ring:${t.focus};--background:${tokens.light.surface};--foreground:${tokens.light['text-primary']};--card:${tokens.light['surface-raised']};--card-foreground:${tokens.light['text-primary']};--border:${tokens.light.border};--input:${tokens.light.border};--muted:${tokens.light['surface-hover']};--muted-foreground:${tokens.light['text-secondary']};--accent:${tokens.light['surface-selected']};--accent-foreground:${tokens.light['text-primary']};--sidebar:${tokens.light['surface-base']};--sidebar-foreground:${tokens.light['text-primary']}}
.dark{--background:${t.surface};--foreground:${t['text-primary']};--card:${t['surface-raised']};--card-foreground:${t['text-primary']};--popover:${t['surface-raised']};--popover-foreground:${t['text-primary']};--secondary:${t['surface-hover']};--secondary-foreground:${t['text-primary']};--muted:${t['surface-hover']};--muted-foreground:${t['text-secondary']};--accent:${t['surface-selected']};--accent-foreground:${t['text-primary']};--border:${t.border};--input:${t.border};--sidebar:${t['surface-base']};--sidebar-foreground:${t['text-primary']};--sidebar-primary:${t.primary};--sidebar-primary-foreground:${t['on-primary']};--sidebar-accent:${t['surface-hover']};--sidebar-accent-foreground:${t['text-primary']};--sidebar-border:${t.border};--sidebar-ring:${t.focus}}
body{font-family:Inter,system-ui,sans-serif}
`;
const rgb = hex => hex.slice(1).match(/../g).map(value=>parseInt(value,16)).join(',');
function formsPalette(p) {
  return Object.entries({background:p['surface-base'],foreground:p.surface,primary:p['text-primary'],'primary-light':p.surface,secondary:p['text-secondary'],accent:p['border-strong'],brand:t.primary}).map(([key,value])=>`--hf-${key}:${rgb(value)}!important`).join(';');
}
const formsCSS = `:root{${formsPalette(tokens.light)}}.dark{${formsPalette(t)}}
body{font-family:Inter,system-ui,sans-serif}
:focus-visible{outline-color:${t.focus}!important}
`;
// Frappe UI retains native light/dark contrast; share workspace action and focus colours.
const crmCSS = `${tokenCSS}
body{font-family:Inter,system-ui,sans-serif}
:root{--blak-crm-accent:${t.primary}}
.btn-primary,.bg-surface-gray-7{background-color:${t.primary}!important;color:${t['on-primary']}!important}
.btn-primary:hover,.bg-surface-gray-7:hover{background-color:${t['primary-hover']}!important}
:focus-visible{outline-color:${t.focus}!important}
`;
const data={'hermes.css':hermesCSS,'chat.css':chatCSS,'projects.css':kaneoCSS,'forms.css':formsCSS,'crm.css':crmCSS};
write('deploy/k3s/micro/51-app-themes.yaml', '# Generated by node scripts/brand/generate.js.\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: blak-app-themes\n  namespace: blak-micro\ndata:\n'+Object.entries(data).map(([name,css])=>`  ${name}: |\n${css.trimEnd().split('\n').map(line=>'    '+line).join('\n')}\n`).join(''));
// Public adapter assets contain branding only, never deployment secrets.
const { APPS } = require('../../apps/portal/catalog');
const shellApps = [{ id:'portal', name:'Workspace', url:'https://portal.workspace.example.com/', backend:'Blak Workspace by Yuma IT' }, ...APPS.filter(a=>a.status==='live' && a.url).map(a=>({id:a.id,name:a.name,url:new URL(a.url,'https://portal.workspace.example.com').href,backend:a.backend}))];
write('services/workspace-shell/logo.svg', logo+'\n');
write('services/workspace-shell/projects-logo.svg', logo+'\n');
write('services/workspace-shell/apps.json', JSON.stringify(shellApps,null,2)+'\n');
write('services/workspace-shell/tokens.json', JSON.stringify({...tokens,chat:{dark:chatRoles(tokens.dark),light:chatRoles(tokens.light)},drive:Object.fromEntries(blakTheme().clients.web.themes.map(theme=>[theme.isDark?'dark':'light',theme.designTokens.roles]))},null,2)+'\n');
