'use strict';
// Generate deployment adapters from the portal's existing Blak palette.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const { blakTheme, tokens, tokenCSS } = require('../../apps/portal/theme');
const check = process.argv.includes('--check');
function write(file, contents) {
  const target = path.join(root, file);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== contents) throw new Error(`Stale generated theme: ${file}`);
  } else fs.writeFileSync(target, contents);
}
const theme = JSON.stringify(blakTheme(), null, 2) + '\n';
write('deploy/k3s/micro/blak-theme/theme.json', theme);
const logo = fs.readFileSync(path.join(root, 'deploy/k3s/micro/blak-theme/assets-logo.svg'), 'utf8').trim();
write('deploy/k3s/micro/50-drive-theme.yaml', '# Generated by node scripts/brand/generate.js. Do not edit.\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: drive-theme\n  namespace: blak-micro\ndata:\n  theme.json: |\n' + theme.trimEnd().split('\n').map(line=>'    '+line).join('\n') + '\n  logo.svg: |\n    ' + logo + '\n');
const t = tokens.dark;
const identityCSS = `${tokenCSS}
body,[class*="background-image"]{background:${t['surface-base']}!important;color:${t['text-primary']}!important;font-family:Inter,system-ui,sans-serif}
[class*="login__main"],[class*="card"],[class*="modal"]{background:${t.surface}!important;border-color:${t['border-subtle']}!important}
button[type=submit],[class*="button"][class*="primary"]{background:${t.primary}!important;color:${t['sand-50']}!important;font-weight:600!important}
button[type=submit]:hover{background:${t['primary-hover']}!important}
h1,h2{color:${t['text-primary']}!important}label{color:${t['text-secondary']}!important}a{color:${t.info}!important}
input{background:${t['surface-raised']}!important;border-color:${t.border}!important;color:${t['text-primary']}!important}input:focus{border-color:${t.focus}!important}
`;
write('scripts/homelab/ak-brand.py', '# Generated by node scripts/brand/generate.js.\nfrom authentik.brands.models import Brand\n\nCSS = """\n' + identityCSS + '"""\nbrand = Brand.objects.get(default=True)\nbrand.branding_title = "Blak ID"\nbrand.branding_custom_css = CSS\nbrand.save()\nfrom authentik.flows.models import Flow\nFlow.objects.filter(slug="default-authentication-flow").update(title="Welcome to Blak ID")\nprint("BRAND_CSS_OK")\n');
// App adapters retain upstream trademarks and interaction patterns.
const hermesCSS = `${tokenCSS}
html,body{font-family:Inter,system-ui,sans-serif!important}
html.dark{--color-gray-50:${t['sand-50']};--color-gray-100:${t['text-primary']};--color-gray-200:${t['text-secondary']};--color-gray-300:${t['text-secondary']};--color-gray-400:${t['text-muted']};--color-gray-500:${t['border-strong']};--color-gray-600:${t.border};--color-gray-700:${t['surface-hover']};--color-gray-800:${t['surface-raised']};--color-gray-850:${t.surface};--color-gray-900:${t.surface};--color-gray-950:${t['surface-base']}}
html:not(.dark){color-scheme:light;--color-white:${tokens.light['surface-raised']};--color-black:${tokens.light['text-primary']};--color-gray-50:${tokens.light.surface};--color-gray-100:${tokens.light['surface-base']};--color-gray-200:${tokens.light['border-subtle']};--color-gray-300:${tokens.light.border};--color-gray-400:${tokens.light['text-muted']};--color-gray-500:${tokens.light['text-secondary']};--color-gray-600:${tokens.light['text-secondary']};--color-gray-700:${tokens.light['text-primary']};--color-gray-800:${tokens.light['text-primary']};--color-gray-900:${tokens.light['text-primary']}}
html.dark body{background:${t.surface};color:${t['text-primary']}}
:focus-visible{outline-color:${t.focus}!important}
::selection{background:${t['water-700']};color:${t['sand-50']}}
`;
const chatCSS = `:root,.rcx-darkmode,[data-theme="dark"]{--rcx-color-button-background-primary-default:${t.primary};--rcx-color-button-background-primary-hover:${t['primary-hover']};--rcx-color-stroke-highlight:${t.focus};--rcx-color-font-info:${t.info};font-family:Inter,system-ui,sans-serif}
.rcx-darkmode,[data-theme="dark"]{--rcx-color-surface-light:${t.surface};--rcx-color-surface-tint:${t['surface-base']};--rcx-color-surface-room:${t.surface};--rcx-color-surface-dark:${t['surface-base']};--rcx-color-font-default:${t['text-primary']};--rcx-color-font-secondary-info:${t['text-secondary']};--rcx-color-stroke-light:${t['border-subtle']}}
`;
// Kaneo uses shadcn design tokens; append after its stylesheet via the deployment adapter.
const kaneoCSS = `:root{--primary:${t.primary};--primary-foreground:${t['sand-50']};--ring:${t.focus};--background:${tokens.light.surface};--foreground:${tokens.light['text-primary']};--card:${tokens.light['surface-raised']};--card-foreground:${tokens.light['text-primary']};--border:${tokens.light.border};--input:${tokens.light.border};--muted:${tokens.light['surface-hover']};--muted-foreground:${tokens.light['text-secondary']};--accent:${tokens.light['surface-selected']};--accent-foreground:${tokens.light['text-primary']};--sidebar:${tokens.light['surface-base']};--sidebar-foreground:${tokens.light['text-primary']}}
.dark{--background:${t.surface};--foreground:${t['text-primary']};--card:${t['surface-raised']};--card-foreground:${t['text-primary']};--popover:${t['surface-raised']};--popover-foreground:${t['text-primary']};--secondary:${t['surface-hover']};--secondary-foreground:${t['text-primary']};--muted:${t['surface-hover']};--muted-foreground:${t['text-secondary']};--accent:${t['surface-selected']};--accent-foreground:${t['text-primary']};--border:${t.border};--input:${t.border};--sidebar:${t['surface-base']};--sidebar-foreground:${t['text-primary']};--sidebar-primary:${t.primary};--sidebar-primary-foreground:${t['sand-50']};--sidebar-accent:${t['surface-hover']};--sidebar-accent-foreground:${t['text-primary']};--sidebar-border:${t.border};--sidebar-ring:${t.focus}}
body{font-family:Inter,system-ui,sans-serif}
`;
const data={'hermes.css':hermesCSS,'chat.css':chatCSS,'projects.css':kaneoCSS};
write('deploy/k3s/micro/51-app-themes.yaml', '# Generated by node scripts/brand/generate.js.\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: blak-app-themes\n  namespace: blak-micro\ndata:\n'+Object.entries(data).map(([name,css])=>`  ${name}: |\n${css.trimEnd().split('\n').map(line=>'    '+line).join('\n')}\n`).join(''));
