'use strict';
function welcomePage(apps) {
  const link = (id, label) => {
    const app = apps.find(app => app.id === id);
    return app ? `<a href="${app.url}">${label}</a>` : label;
  };
  return `<article class="getting-started"><p class="eyebrow">Blak Workspace · Getting started</p><h1>Your first steps</h1><p class="guide-intro">One Blak ID connects your files, knowledge and team. Start here, then return whenever you need a hand.</p>
<nav class="guide-links" aria-label="Guide contents"><a href="#identity">Sign in</a><a href="#files">Files and documents</a><a href="#knowledge">Knowledge and teamwork</a><a href="#search-help">Search</a><a href="#hermes-help">Hermes</a><a href="#vault-help">Vault</a></nav>
<section id="identity"><h2>1. Get comfortable with Blak ID</h2><p>Blak ID is your shared sign-in. Open apps from the workspace launcher to use your existing session automatically. Only apps granted to your account appear. Ask your administrator if an app is missing.</p><p>Use the app launcher to switch tools. Change your theme with the sun or moon button. Use <strong>Sign out of workspace</strong> to end app sessions and Blak ID together. Manage your password and account through <a href="/account">Blak ID</a>.</p></section>
<section id="files"><h2>2. Add a file, then open a document</h2><ol><li>Open ${link('drive', 'Blak Drive')} and upload a file or create a document.</li><li>Open a document in Drive to edit it with Blak Docs. Changes save back to Drive.</li><li>Use Drive’s sharing controls to choose who can access it. A workspace account does not make every file public.</li></ol></section>
<section id="knowledge"><h2>3. Give your team a shared starting point</h2><p>Use ${link('sites', 'Blak Knowledge')} for notes, how-to pages and team documentation. Create a collection and publish your first page there.</p><p>Track tasks in ${link('projects', 'Blak Projects')}, talk in ${link('chat', 'Blak Chat')}, collect responses with ${link('forms', 'Blak Forms')}, and sketch ideas in ${link('draw', 'Blak Draw')}.</p></section>
<section id="search-help"><h2>4. Find your work</h2><p>Enter a word or document title in the top search box and press Enter, or open ${link('search', 'Blak Search')}. Results show the source app and a link back to the original.</p><p>Connected content refreshes every five minutes. Only content synced for your account appears. If a new file is missing, check ${apps.some(a=>a.id==='hermes') ? '<a href="/sync">connection status</a>' : 'connection status'} and allow one sync cycle.</p></section>
<section id="hermes-help"><h2>5. Ask Blak Hermes</h2><ol><li>Open ${link('hermes', 'Blak Hermes')} and continue with Blak ID.</li><li>Select <strong>Blak Workspace</strong> in the model selector to ask about your connected content.</li><li>Try “Summarise my project tasks” or ask a specific question about a document.</li><li>Check the cited sources before relying on an answer. If content is missing, check ${apps.some(a=>a.id==='hermes') ? '<a href="/sync">connection status</a>' : 'connection status'}.</li></ol><p>Blak Hermes handles everyday questions. Blak Workspace searches your connected content. Both run locally. Document questions can take longer than a simple chat. Keep the page open while the answer streams.</p></section>
<section id="vault-help"><h2>6. Keep sensitive information in Blak Vault</h2><ol><li>Open ${link('vault', 'Blak Vault')} and sign in with Blak ID. Enrol an authenticator app or passkey if prompted.</li><li>Choose a unique master password. Blak ID proves who you are; this separate password unlocks your encrypted vault. Keep your recovery information offline.</li><li>Use a login item for passwords, a secure note for API keys or certificates, and attachments for sensitive files. Choose your organisation and a shared collection when the group needs access.</li><li>Your administrator grants <strong>reader</strong>, <strong>writer</strong> or <strong>admin</strong> access through Blak ID. Shared access starts after a vault owner confirms your membership and encryption key.</li></ol><p>Readers can view shared items; writers can edit them; admins manage the organisation. Personal vault items remain private. Removing access cannot erase secrets someone already downloaded—rotate exposed passwords and keys when needed.</p><p>Use <strong>Lock</strong> or <strong>Log out</strong> inside Vault when finished. Workspace sign-out does not erase an unlocked vault in another tab or an offline Bitwarden client. Vault contents never enter Blak Search or Hermes.</p></section>
<section><h2>Need a hand?</h2><p>For sign-in trouble, start again from <a href="/">Blak Workspace</a> and use Blak ID. For missing data, check the source app first, then connection status. Ask your workspace administrator to connect or repair your account’s sources.</p></section></article>`;
}
module.exports = { welcomePage };
