'use strict';
function welcomePage(apps) {
  const url = id => apps.find(app => app.id === id).url;
  return `<article class="getting-started"><p class="eyebrow">Blak Workspace · Getting started</p><h1>Your first steps</h1><p class="guide-intro">One Blak ID connects your files, knowledge and team. Start here, then return whenever you need a hand.</p>
<nav class="guide-links" aria-label="Guide contents"><a href="#identity">Sign in</a><a href="#files">Files and documents</a><a href="#knowledge">Knowledge and teamwork</a><a href="#search-help">Search</a><a href="#hermes-help">Hermes</a></nav>
<section id="identity"><h2>1. Get comfortable with Blak ID</h2><p>Blak ID is your shared sign-in. When an app offers <strong>Continue with Blak ID</strong> or <strong>Login with Blak ID</strong>, use it. Your existing session usually signs you straight in.</p><p>Use the app launcher to switch tools. Change your theme with the sun or moon button. Manage your password and account through <a href="${url('idp')}">Blak ID</a>.</p></section>
<section id="files"><h2>2. Add a file, then open a document</h2><ol><li>Open <a href="${url('drive')}">Blak Drive</a> and upload a file or create a document.</li><li>Open a document in Drive to edit it with Blak Docs. Changes save back to Drive.</li><li>Use Drive’s sharing controls to choose who can access it. A workspace account does not make every file public.</li></ol></section>
<section id="knowledge"><h2>3. Give your team a shared starting point</h2><p>Use <a href="${url('sites')}">Blak Knowledge</a> for notes, how-to pages and team documentation. Create a collection and publish your first page there.</p><p>Track tasks in <a href="${url('projects')}">Blak Projects</a>, talk in <a href="${url('chat')}">Blak Chat</a>, collect responses with <a href="${url('forms')}">Blak Forms</a>, and sketch ideas in <a href="${url('draw')}">Blak Draw</a>.</p></section>
<section id="search-help"><h2>4. Find your work</h2><p>Enter a word or document title in the top search box and press Enter, or open <a href="/search">Blak Search</a>. Results show the source app and a link back to the original.</p><p>Connected content refreshes every five minutes. Only content synced for your account appears. If a new file is missing, check <a href="/sync">connection status</a> and allow one sync cycle.</p></section>
<section id="hermes-help"><h2>5. Ask Blak Hermes</h2><ol><li>Open <a href="${url('hermes')}">Blak Hermes</a> and continue with Blak ID.</li><li>Select <strong>Blak Workspace</strong> in the model selector to ask about your connected content.</li><li>Try “Summarise my project tasks” or ask a specific question about a document.</li><li>Check the cited sources before relying on an answer. If content is missing, check <a href="/sync">connection status</a>.</li></ol><p>Blak Hermes handles everyday questions. Blak Workspace searches your connected content. Both run locally. Document questions can take longer than a simple chat. Keep the page open while the answer streams.</p></section>
<section><h2>Need a hand?</h2><p>For sign-in trouble, start again from <a href="/">Blak Workspace</a> and use Blak ID. For missing data, check the source app first, then connection status. Ask your workspace administrator to connect or repair your account’s sources.</p></section></article>`;
}
module.exports = { welcomePage };
